#include "dar/worker/worker_service.h"

#include <string>
#include <utility>

#include "dar/serialization/serialization.h"

namespace dar
{
namespace
{

grpc::Status ApplicationFailure(
    const Status& status,
    proto::v1::LaunchTaskResponse* response)
{
    // mutable_status() is generated automatically by Protobuf
    /**
     * In worker.proto: 
     * message LaunchTaskResponse {
    Status status = 1;
    }
    in common.proto: 
    message Status {
    StatusCode code = 1;
    string message = 2;
    }

    when protoc processes this, it generates a C++ class:
    class LaunchTaskResponse {
public:
    const Status& status() const;

    Status* mutable_status();

    // other generated functions...
};
    (serialization.cpp): 
    void ToProto(
    const dar::Status& source,
    proto::v1::Status* destination)
{
    destination->set_code(...);
    destination->set_message(source.message());
}
     */
    // mutable_status(): give me a mutable pointer to the Status message stored inside this LaunchTaskResponse, so I can modify it
    /**
     * LaunchTaskResponse
│
└── status
    │
    ├── code
    └── message

response
   │
   │ mutable_status()
   ▼
pointer to status
   │
   ▼
ToProto(dar_status, pointer)
   │
   ├── set_code(...)
   └── set_message(...)
     */
    serialization::ToProto(status, response->mutable_status());

    // Transport succeeded.
    //
    // The DAR operation itself failed, but the RPC was successfully
    // delivered, decoded, processed, and answered.
    return grpc::Status::OK;
}

}  // namespace

WorkerServiceImpl::WorkerServiceImpl(
    Runtime& runtime,
    HandlerRegistry& registry,
    ResultReporter* result_reporter)
    : runtime_(runtime), 
    registry_(registry), 
    result_reporter_(result_reporter)
    {
        runtime_.SetCompletionCallback(
            [this](const TaskCompletion& completion)
            {
                ExecutionID remote_execution_id;

                {
                    std::lock_guard<std::mutex> lock(executions_mu_);

                    const auto it = remote_executions_.find(completion.task_id);

                    if(it == remote_executions_.end())
                    {
                        return;
                    }

                    remote_execution_id = it->second;

                    remote_executions_.erase(it);
                }

                (void)result_reporter_->Report(
                    completion.task_id,
                    remote_execution_id,
                    completion.state,
                    completion.status,
                    completion.result,
                    std::chrono::seconds(2)
                );
            }
        );
    }

grpc::Status WorkerServiceImpl::LaunchTask(
    grpc::ServerContext*,
    const proto::v1::LaunchTaskRequest* request,
    proto::v1::LaunchTaskResponse* response)
{
    if(request == nullptr || response == nullptr)
    {
        return grpc::Status(
            grpc::StatusCode::INTERNAL,
            "gRPC supplied null request/response");
    }

    // task() is an accessor directly generated by Protobuf
    /**
     * Protobuf generate:
     * class LaunchTaskRequest {
public:
    // Read-only access
    const TaskDescriptor& task() const;

    // Mutable access
    TaskDescriptor* mutable_task();
};
     */
    // Returns a const reference to the TaskDescriptor contained inside that request
    const proto::v1::TaskDescriptor& wire_task =
        request->task();

    // --------------------------------------------------------
    // 1. Decode distributed identity
    // --------------------------------------------------------

    TaskID task_id;
    Status status = serialization::FromProto(
        wire_task.task_id(),
        &task_id);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    TenantID tenant_id;
    status = serialization::FromProto(
        wire_task.tenant_id(),
        &tenant_id);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    AgentID agent_id;
    status = serialization::FromProto(
        wire_task.agent_id(),
        &agent_id);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    // Validate the remote execution identity even though Phase 1
    // currently creates its own local execution attempt when the
    // scheduler performs placement.
    ExecutionID remote_execution_id;
    status = serialization::FromProto(
        wire_task.execution_id(),
        &remote_execution_id);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    if(wire_task.attempt() == 0)
    {
        return ApplicationFailure(
            Status::InvalidArgument(
                "task attempt must be greater than zero"),
            response);
    }

    // --------------------------------------------------------
    // 2. Decode resources
    // --------------------------------------------------------

    ResourceSet resources;

    status = serialization::FromProto(
        wire_task.resources(),
        &resources);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    // --------------------------------------------------------
    // 3. Resolve distributed code identity
    // --------------------------------------------------------

    if(wire_task.entrypoint().empty())
    {
        return ApplicationFailure(
            Status::InvalidArgument(
                "task entrypoint cannot be empty"),
            response);
    }

    RegisteredHandler registered_handler;

    // perform lookup from distributed function name to actual local C++ executable code
    status = registry_.Resolve(
        wire_task.entrypoint(),
        &registered_handler);

    if(!status.ok())
    {
        return ApplicationFailure(status, response);
    }

    // --------------------------------------------------------
    // 4. Construct the existing Phase-1 TaskSpec
    // --------------------------------------------------------

    TaskSpec spec;

    spec.tenant_id = tenant_id;
    spec.id = task_id;
    spec.agent_id = agent_id;
    spec.name = wire_task.name();

    // ResourceRequest wraps ResourceSet in your Phase-1 model.
    spec.resources = ResourceRequest(std::move(resources));

    // Phase 3 does not yet implement distributed ObjectRef inputs.
    spec.inputs.clear();

    // --------------------------------------------------------
    // 5. Bind wire payload -> local Phase-1 TaskHandler
    // --------------------------------------------------------

    const std::string payload = wire_task.payload();
    const std::string payload_media_type =
        wire_task.payload_media_type();

    TaskHandler local_handler =
        [
            // of RegisteredHandler type(handler_registry.h)
            handler = std::move(registered_handler),
            payload,
            payload_media_type
        ](
            const TaskSpec& local_spec,
            RuntimeContext& context,
            std::string* result) mutable -> Status
        {
            return handler(
                local_spec,
                context,
                payload,
                payload_media_type,
                result);
        };

    if(result_reporter_!=nullptr)
    {
        std::lock_guard<std::mutex> lock(executions_mu_);

        remote_executions_[task_id] = remote_execution_id;
    }
    // --------------------------------------------------------
    // 6. CROSS THE ARCHITECTURAL BOUNDARY
    // --------------------------------------------------------

    status = runtime_.Submit(
        std::move(spec),
        std::move(local_handler));

    if(!status.ok() && result_reporter_ != nullptr)
    {
        std::lock_guard<std::mutex> lock(executions_mu_);

        remote_executions_.erase(task_id);
    }

    serialization::ToProto(status, response->mutable_status());

    // LaunchTask is admission, not task completion.
    //
    // If Runtime::Submit() returned OK, the Phase-1 runtime now owns
    // the task and its scheduler/worker machinery proceeds normally.
    return grpc::Status::OK;
}

}  // namespace dar