syntax = "proto3";

package dar.proto.v1;

import "google/protobuf/timestamp.proto";
import "common.proto";

enum NodeState
{
  NODE_STATE_UNSPECIFIED = 0;
  NODE_STATE_ALIVE = 1;
  NODE_STATE_SUSPECT = 2;
  NODE_STATE_DEAD = 3;
}

message NodeDescriptor {
  NodeId node_id = 1;
  string worker_endpoint = 2;
  ResourceSet total_resources = 3;
  ResourceSet reported_available_resources = 4;
  uint64 incarnation = 5;
  NodeState state = 6;
  uint32 running_tasks = 7;
  google.protobuf.Timestamp last_heartbeat = 8;
  map<string, string> labels = 9;
}

message NodeHeartbeat {
  NodeId node_id = 1;
  uint64 incarnation = 2;
  ResourceSet available_resources = 3;
  uint32 running_tasks = 4;
  google.protobuf.Timestamp sent_at = 5;
}