#include "dar/node/node_manager.h"

#include "dar/serialization/serialization.h"

#include "worker.grpc.pb.h"

namespace dar
{

    // NodeRegistry: StoreNode (struct, contain 1 NodeRecord-all information about a node), schedulable_pool_(ResourceSet)
    // rpc_client: connection_pool(contains: A map of endpoints to gRPC channels)
NodeManager::NodeManager(
    NodeRegistry& registry,
    RpcClient& rpc_client)
    : registry_(registry),
      rpc_client_(rpc_client)
{
}


Status NodeManager::RegisterNode(NodeRecord node)
{
    return registry_.RegisterNode(
        std::move(node));
}


Status NodeManager::DispatchTask(
    const NodeRecord& node,
    const proto::v1::TaskDescriptor& task,
    std::chrono::milliseconds timeout)
{
    // Channel(): either return a shared_pointer to the channel with given name, or create a new one and return it
    auto channel =
        rpc_client_.Channel(
            node.worker_endpoint);

    // NewStub() is automatically generated by gRPC from worker.proto 
    /**
class WorkerService
{
public:

    // Client-side interface
    class Stub
    {
    public:
        grpc::Status LaunchTask(...);
        grpc::Status CancelTask(...);
        grpc::Status GetWorkerInfo(...);
    };

    // Factory for creating the client Stub
    static std::unique_ptr<Stub> NewStub(
        const std::shared_ptr<grpc::ChannelInterface>& channel);

    // Server-side interface
    class Service : public grpc::Service
    {
        ...
    };
};
     */
    // Create a client object for WorkerService that sends its RPCs through this particular gRPC channel
    /**
     * worker.proto
    │
    │ protoc + grpc_cpp_plugin
    ▼
worker.grpc.pb.h / .cc
    │
    ├── WorkerService::Service
    │       ↑
    │       server-side API
    │
    ├── WorkerService::Stub
    │       ↑
    │       client-side API
    │
    └── WorkerService::NewStub(channel)
            ↑
            factory that creates the client Stub
     */
    // Why do we need both Channel and Stub
    // Channel: How do I communicate with that server (Ex: Channel: target(127.0.0.1:50051))
    // Stub: which service and RPC methods do I want to call through that communication path
    /**
WorkerService client
│
├── LaunchTask(...)
├── CancelTask(...)
└── GetWorkerInfo(...)
        │
        ▼
      channel
        │
        ▼
127.0.0.1:50051
     */
    auto stub =
        proto::v1::WorkerService::NewStub(
            channel);

    proto::v1::LaunchTaskRequest request;

    // Protobuf: TaskDescriptor* mutable_task(), so use *request.mutable() task return a value on the pointer
    *request.mutable_task() = task;

    proto::v1::LaunchTaskResponse response;

    // CreateContext() create a unique_pointer to a grpc::ClientContext(configure, control, and insepct individual RPC invocations)
    // set the deadline to be after timeout:Put a maximum time limit on that specific RPC call
    auto context =
        rpc_client_.CreateContext(timeout);

    // On client-side, use RPC call to launch a task with context, the request, and an &response to receive the output(LaunchTaskResponse type from worker.proto)
    // context.get() -> ClientContext
    // request -> data sent to WorkerService
    // &response -> where WorkerService's response is written
    // transport_status: Did the gRPC communication itself succeed
    // response.status(): Did DAR's launchTask operation succeed
    
    const grpc::Status transport_status =
        stub->LaunchTask(
            context.get(),
            request,
            &response);
    // When NodeManager does: stub->LaunchTask(...)
    /**
serialize LaunchTaskRequest
        ↓
send across network
        ↓
gRPC server receives it
        ↓
find WorkerService
        ↓
call WorkerServiceImpl::LaunchTask()
        ↓
Runtime::Submit()
        ↓
construct LaunchTaskResponse
        ↓
serialize response
        ↓
send across network
        ↓
client receives response
        ↓
stub->LaunchTask(...) returns
     */

    if(!transport_status.ok())
    {
        return Status::Unavailable(
            "LaunchTask RPC failed: " +
            transport_status.error_message());
    }

    return serialization::FromProtoStatus(
        response.status());
}

}  // namespace dar